
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 23;
  public static final int INTEGER = 37;
  public static final int LPAREN = 21;
  public static final int INT = 13;
  public static final int PRINTLN = 15;
  public static final int MINUS = 32;
  public static final int STATIC = 3;
  public static final int RPAREN = 22;
  public static final int NOT = 36;
  public static final int SEMICOLON = 29;
  public static final int AND = 33;
  public static final int LESSTHAN = 34;
  public static final int COMMA = 27;
  public static final int CLASS = 7;
  public static final int PLUS = 31;
  public static final int MAIN = 5;
  public static final int IF = 10;
  public static final int THIS = 20;
  public static final int ID = 38;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int BOOLEAN = 14;
  public static final int RETURN = 9;
  public static final int EQUAL = 35;
  public static final int RBRACKET = 24;
  public static final int TRUE = 17;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int VOID = 4;
  public static final int TIMES = 30;
  public static final int LBRACE = 25;
  public static final int ELSE = 11;
  public static final int WHILE = 12;
  public static final int PUBLIC = 2;
  public static final int RBRACE = 26;
  public static final int EXTENDS = 8;
  public static final int STRING = 6;
  public static final int FALSE = 18;
  public static final int LENGTH = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "CLASS",
  "EXTENDS",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "INT",
  "BOOLEAN",
  "PRINTLN",
  "LENGTH",
  "TRUE",
  "FALSE",
  "NEW",
  "THIS",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "DOT",
  "SEMICOLON",
  "TIMES",
  "PLUS",
  "MINUS",
  "AND",
  "LESSTHAN",
  "EQUAL",
  "NOT",
  "INTEGER",
  "ID"
  };
}

